### ISSUE TITLE
关于参数的建议

### ISSUE THREAD

**Issue by NewFuture** [ufologist/weappdevtools-cli#1]
这个工具很有意思 👍 

upload上传的参数有两个建议：

1. [x]  desc 可以默认取  commit message (short+long)，env如果没有设置可以隐藏掉
这样可以尽量减少重复输入和参数尽量自动化
2. [x] version 除了 小程序目录的 package.json 建议尝试提取一下当前路径的package.json的version或者运行的npm_package_version, 比如在输出目标项目不包含的package.json的场景，无法获取到版本信息(如 https://github.com/NewFuture/miniprogram-template)

**Comment by ufologist** [comment]
关于 `desc` 默认取 commit message (short+long), 这个建议是好的,
但由于 commit message 字符串的长度不可控, 可能会有超出小程序上传提交时 `--upload-desc` 参数对字符串的限制(具体规则没有测试过, 但有风险), 造成无法上传, 因此还是不要直接拼接到 `desc` 为好.

建议调整一下获取 commit message 的规则, 例如截取一定的字符数, 再提 PR

**Comment by NewFuture** [comment]
> 建议调整一下获取 commit message 的规则, 例如截取一定的字符数, 再提 PR

这个地方貌似现在的开发工具会截取前100个

这里没必要截取一次，这个规则开发工具维护更合适，开发工具这个也可能修改

**Comment by ufologist** [comment]
目前开发者工具上`项目备注`是限制了只能输入 100 个字符, 但 `weappdevtools-cli` 底层是通过开发者工具提供的 `cli` 接口来调用的, **实测可以绕过这个限制**

![QQ截图20190601112540](https://user-images.githubusercontent.com/167221/58743406-2c37e480-8463-11e9-8e20-48a15ddf341d.png)

因此理论上如果微信的上传接口不做限制, 就有可能导致上传失败(例如项目备注输入了超多字符串的情况), 不过相信微信这样的大厂对上传接口是做了严格的异常边界测试的, 但我还是建议在工具中做一次截取.

我会先合并 PR, 再调整一下代码

**Comment by NewFuture** [comment]
有一定道理

1. 先要确定边界
2. 如果需要设置上限最好在这里限制

https://github.com/ufologist/weappdevtools-cli/blob/c38b33d27add6d0e749b1229fa546e37649012d1/src/wechatdevtools-cli.js#L141

**Comment by ufologist** [comment]
已经在 `1.1.0` 版本中实现了
